# Generated by Django 3.2.7 on 2021-09-22 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210921_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binanceauth',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='binance', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
