# Generated by Django 5.0.6 on 2024-06-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_token"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FtxAuth",
        ),
    ]
