# Generated by Django 3.2.8 on 2021-10-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange", "0002_portfolio_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioasset",
            name="realized_pnl",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=64, verbose_name="realized_pnl"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portfolioasset",
            name="unrealized_pnl",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=64,
                verbose_name="unrealized_pnl",
            ),
            preserve_default=False,
        ),
    ]
