# Generated by Django 3.2.8 on 2021-10-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange", "0003_auto_20211010_2253"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioasset",
            name="avg_charge",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=64,
                verbose_name="average charge",
            ),
            preserve_default=False,
        ),
    ]
