# Generated by Django 3.2.8 on 2021-10-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange", "0006_portfolioasset_exchanged_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolioasset",
            name="exchanged_amount",
        ),
        migrations.AddField(
            model_name="portfolioasset",
            name="buy_amount",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=64, verbose_name="buy amount"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portfolioasset",
            name="sell_amount",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=64, verbose_name="sell amount"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="portfolioasset",
            name="amount",
            field=models.DecimalField(decimal_places=8, max_digits=64, verbose_name="amount (quantity)"),
        ),
        migrations.AlterField(
            model_name="portfolioasset",
            name="value",
            field=models.DecimalField(decimal_places=8, max_digits=64, verbose_name="value (USD)"),
        ),
    ]
