# Generated by Django 3.2.8 on 2021-10-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange", "0010_auto_20211018_0049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="symbol",
            field=models.CharField(max_length=16, unique=True, verbose_name="symbol"),
        ),
    ]
