# Generated by Django 3.2.7 on 2021-09-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_auto_20210921_1406"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binanceauth",
            name="api_key",
            field=models.CharField(max_length=256, verbose_name="api key"),
        ),
        migrations.AlterField(
            model_name="binanceauth",
            name="api_secret",
            field=models.CharField(max_length=256, verbose_name="api secret"),
        ),
    ]
