# Generated by Django 3.2.8 on 2021-10-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_auto_20211011_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioasset',
            name='exchanged_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=64, verbose_name='exchanged amount'),
            preserve_default=False,
        ),
    ]
