# Generated by Django 3.2.8 on 2021-10-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_auto_20211018_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=64, verbose_name='price (USD)'),
        ),
    ]
