# Generated by Django 3.2.8 on 2021-10-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_asset_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='ticker',
        ),
        migrations.AddField(
            model_name='asset',
            name='symbol',
            field=models.CharField(default='BTC', max_length=16, verbose_name='symbol'),
            preserve_default=False,
        ),
    ]
