name: Build & Deploy Backend

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

env:
  PROJECT_NAME: cryptopatro

jobs:
  build_and_push:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: backend
          push: true
          tags: ${{ github.repository_owner }}/${{ env.PROJECT_NAME }}:${{ github.sha }}
          platforms: linux/arm64

  deploy_to_production:
    name: Deploy to production
    needs: build_and_push
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: production
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - name: Netbird Connect
        id: netbird
        uses: Alemiz112/netbird-connect@v1
        with:
          setup-key: ${{ secrets.NETBIRD_SETUP_KEY }}
          hostname: github-runners-${{ github.run_id }}

      - name: Deploy Helm chart
        uses: vimeda/helm@v1
        env:
          KUBECONFIG_FILE: "${{ secrets.KUBECONFIG }}"
        with:
          release: ${{ env.PROJECT_NAME }}
          namespace: default
          chart: backend/k8s-helm
          values: |
            image.tag: ${{ github.sha }}
