name: Build & Deploy Backend

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

env:
  PROJECT_NAME: cryptopatro

jobs:
  build_and_push:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: backend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ github.repository_owner }}/${{ env.PROJECT_NAME }}:${{ github.sha }}
          platforms: linux/arm64

  deploy_to_production:
    name: Deploy to production
    needs: build_and_push
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: production
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up kube config
        run: |
          mkdir -p ~/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 -d > ~/.kube/config

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Deploy Helm chart
        env:
          CHART_PATH: k8s-helm
          IMAGE_TAG: ${{ github.sha }}
        run: helm upgrade $PROJECT_NAME $CHART_PATH --set image.tag=$IMAGE_TAG -n default --install --wait
