name: Build & Push Backend

on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: cryptopatro

jobs:
  build_and_push:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ github.repository_owner }}/${{ env.PROJECT_NAME }}:${{ github.sha }},${{ github.repository_owner }}/${{ env.PROJECT_NAME }}:latest
          platforms: linux/arm64,linux/amd64
