name: Build & Deploy VueJS to GitHub Pages

on: workflow_dispatch

env:
  DOMAIN: cryptopatro.gezici.me
  GITHUB_EMAIL: doruk@gezici.me

jobs:
  deploy:
    name: Build & Deploy VueJS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build & Deploy
        shell: bash
        run: |
          cd frontend
          npm ci
          npm run build
          cd dist
          ln -s index.html 404.html
          # echo $DOMAIN > CNAME
          git config --global user.email $GITHUB_EMAIL
          git config --global user.name $GITHUB_ACTOR
          git init
          git add -A
          git commit -m 'Deploy to GitHub Pages'
          git push -f https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git main:gh-pages
